### ISSUE TITLE
Can't translate

### ISSUE THREAD

**Issue by marten** [zooniverse/pandora#103]
Steps undertaken:

* Go to pandora.zooniverse.org
* Log in and allow oauth access
* Click project name
* Click the language dropdown
* Type Du, click Dutch

Expected result:

English text loads up on the left, text boxes for Dutch text on the right.

Actual result:

No text displayed. No list of workflows displayed either.

![image](https://user-images.githubusercontent.com/277/43639916-c86134b0-9715-11e8-87fb-57c8a9de81a3.png)

**Comment by eatyourgreens** [comment]
Turns out this was due to translations not existing in Panoptes for that project, so I'm going to close this as not a UI issue.

**Comment by marten** [comment]
Not sure, should the UI be showing an error message when it doesn't get translations back from the API?

**Comment by eatyourgreens** [comment]
If the API returns an error response then sure, but here the response is a 200.

**Comment by eatyourgreens** [comment]
There’s a Panoptes bug that stops editing at the moment. Right now, saving a translation causes a 500 error (which breaks the API client 😔.)
