### ISSUE TITLE
Missing information from Project page causes bug

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/pandora#115]
If some of the fields from the project page (e.g. the researcher quote) are missing, Pandora throws a not-immediately comprehensible error.

**Comment by eatyourgreens** [comment]
What was the error message? No problems here adding a new language to Diagnosis London. 
![Screenshot of Diagnosis London project details in the translations editor.](https://user-images.githubusercontent.com/59547/51524898-06e8f900-1e27-11e9-8884-adc672750c59.png)

**Comment by eatyourgreens** [comment]
This might be a duplicate of #130.

**Comment by eatyourgreens** [comment]
I'm pretty sure this was fixed by #134.
