### ISSUE TITLE
strange display in Safari browser?

### ISSUE THREAD

**Issue by sheishistoric** [zooniverse/pandora#126]
Works fine in Chrome, but was trying to demo using Safari & had this display
<img width="1195" alt="screen shot 2019-02-14 at 12 28 04 pm" src="https://user-images.githubusercontent.com/8959416/52805207-150bed00-3054-11e9-85b0-9b7ef2b6f9ed.png">

**Comment by eatyourgreens** [comment]
Can I ask which version of Safari you're using? Here's what I see in Safari 12.
![Screenshot showing the project home page without problems in Safari 12.](https://user-images.githubusercontent.com/59547/53498545-6bd6e500-3a9e-11e9-8cec-63ffb5ce1cee.png)

**Comment by eatyourgreens** [comment]
The layout's using Grommet v1 (https://v1.grommet.io/). I'm not sure if that works in Safari 10. It should work in 11 or 12.

**Comment by sheishistoric** [comment]
Okay, thanks. I can't update Safari on this computer due to institutional restrictions, but I will let any of our translators know that in the future.
