### ISSUE TITLE
TypeError: Cannot read property translated_type of undefined

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#130]
This error is preventing @yshish from adding new translations. It seems to be reproducible across several projects.

![Place the face](https://panoptes-uploads.zooniverse.org/production/project_attached_image/51a493f2-263e-4fbf-bf3f-b116d8fb7de9.png)
![Whales as Individuals: research page](https://panoptes-uploads.zooniverse.org/production/project_attached_image/df5f95ab-d5ad-4033-9d50-cc739dcb0686.png)
![Whales as Individuals: dashboard](https://panoptes-uploads.zooniverse.org/production/project_attached_image/c260782c-0024-4db3-a88f-44c8c1030ce9.jpeg)

**Comment by yshish** [comment]
Using latest Chromium on Ubuntu, if that helps. Trying it on a tablet using Android... Ah, happens there as well. :/

**Comment by eatyourgreens** [comment]
The underlying issue seems to be a problem with Panoptes. The request for the original, English version of the projects is returning an empty array.
https://www.zooniverse.org/api/translations?http_cache=true&translated_type=Project&translated_id=669

**Comment by eatyourgreens** [comment]
This is an error in Panoptes, so I can't fix it here. I've updated the error message so that it tells us that the English version doesn't exist for the project.
