### ISSUE TITLE
Editor text box shows the wrong text

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#29]
State isn't being correctly updated somewhere, so the text box shows the last field edited when I go to edit a new field.

eg. here I'm editing the project description, after editing the title, but the text input still shows the project title.
![Screenshot of the editor dialog showing the wrong text being displayed in the text input](https://user-images.githubusercontent.com/59547/28115617-8eec3192-66fd-11e7-84d9-37434266331a.png)

**Comment by simoneduca** [comment]
My bad. Regarding `input`, I followed [your suggestion](https://github.com/zooniverse/pandora/commit/bcfce00b5b3c6b4b0c00fb2511db10ae6bd3e713#commitcomment-23042009) without thinking and added `value={this.state.translationText}`, but I don't think it was right. So I'll remove that.
It currently happens for `MarkdownEditor` fields, investigating that now.

**Comment by eatyourgreens** [comment]
I think you've forgotten to set `translationText` before editing. Should be a simple fix. 

`value` on both inputs should be set to the text that you are currently editing.
