### ISSUE TITLE
Localisable resources in Panoptes

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#6]
Just a list of resources that would need to be translated in order to create a full translation of a Panoptes project.

 - [x] FieldGuide
 - [ ] OrganizationContents
 - [x] ProjectContents
 - [x] ProjectPage
 - [x] Tutorial
- [x] WorkflowContents

I think that's got them all, but feel free to add any that I've missed.

**Comment by simoneduca** [comment]
I've added `OrganizationContents`, as a follow to this https://github.com/zooniverse/pfe-lab/issues/53

**Comment by eatyourgreens** [comment]
I'm going to close this and open a new issue for translating organisations.
