### ISSUE TITLE
Access translations as admin

### ISSUE THREAD

**Issue by camallen** [zooniverse/pandora#61]
Instead of adding collabs / translator roles for internal team members it would be nice to use an admin mode to access translations resources in the UI, similar to how PFE works.

**Comment by eatyourgreens** [comment]
I think this could be fixed by using the header and footer from [zooniverse/Zooniverse-React-Components](/zooniverse/Zooniverse-React-Components)

**Comment by eatyourgreens** [comment]
Admin mode in PFE now gives you links from the project builder to translations for any project. I think all that's left to do for this issue is to add the admin flag to API requests here, if set.
