### ISSUE TITLE
Page size is too small for user's project list API request

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/pandora#627]
## Describe Current Behavior
As a logged in user, when I visit the https://translations.zooniverse.org/ homepage, I see a list of organizations and projects where I am owner or collaborator.  However, the list of projects is truncated to 20 due to the lack of pagination in results from Panoptes API and a relatively small current limit. Note that most users are not owner/collab on >20 projects, but it is an issue for Zoo team members.

## Describe Desired Behavior
The projects list should include more than 20 entries.  Rather than adding next/previous page functionality, it should be sufficient to increase the number of projects initially fetched from 20 to 100 (max allowed by Panoptes API).

**Comment by eatyourgreens** [comment]
Searching for a project, by name, would be nice too.
