### ISSUE TITLE
Ability to translate 'continue' 'back' and other buttons 

### ISSUE THREAD

**Issue by VVH** [zooniverse/pandora#70]
Couldn't see this change in https://www.zooniverse.org/projects/wildcam/wildcam-darien/classify?language=es for example. If it is a feature and isn't already clearly stated in the guidelines for project translators to change the text on the buttons, it would be worth adding this to documentation.

**Comment by eatyourgreens** [comment]
Pandora is an app for editing the text that project owners create in the project builder. User interface text, like button labels, is stored in PFE in [`/app/locales`](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/locales) eg. https://www.zooniverse.org/projects/wildcam/wildcam-darien/classify?language=nl

Spanish can be added to PFE by opening a PR with edits to the Spanish language file.
