### ISSUE TITLE
Show the translation as blank if it hasn't been translated

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#92]
It's easier to quickly see what needs to be done if untranslated fields are blank.

The markdown editor should probably still open with the original text, otherwise translators will have to create the markdown code from scratch.

**Comment by snblickhan** [comment]
I can confirm this is true -- the Geniza team have not realized certain things weren't translated because it auto-loads the English text.

**Comment by snblickhan** [comment]
Actually, have just thought of a use case in which it's helpful to have certain text show up as it is in the original -- SotCG project have [workflows](https://pandora.zooniverse.org/#/project/5042/workflow/6600) for which the questions need translation, but the responses need to remain in the original language. 

I'd say this could be rectified by having the translation space blank, but by adding some sort of "keep original" button? In the interim it's fine to copy/paste, but something to consider down the line?

**Comment by eatyourgreens** [comment]
I'm thinking the editor should always open with text in it, otherwise the Markdown fields will be horrible for volunteers to create from scratch.

It shouldn't be a problem to hide the translation text in the initial view, if the original and translation are exactly the same.

#11 notes that we still need to figure out how to flag up translations that are out-of-date with respect to the original.

**Comment by eatyourgreens** [comment]
I'm playing around a bit with this idea now. If I save a translation as the original text, the app thinks I haven't edited it so doesn't show my edit. Eg. I save Galaxy Zoo's title, in French, as Galaxy Zoo but the field still shows blank in the translation editor.

We haven't really got a good way of indicating which fields need working on, at the moment.

**Comment by eatyourgreens** [comment]
Creating a new translation copies the original language strings across here:
https://github.com/zooniverse/pandora/blob/878d02777df566498134ba343756545e1e09453d/src/ducks/resource.js#L99-L102

We can default strings to an empty object instead, but copy the original text across when you open the editor. That would get around the problem of not wanting to recreate long Markdown fields from scratch.

I think there's still a need to the API response to flag up how complete a translation resource is, so that we can tell which partially completed ones still need work. That might be a case of setting a metadata flag on the translation, in the editor, and saving it back to Panoptes with the translation.
