### ISSUE TITLE
Open the editor inline

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pandora#93]
Should the app open the editor inline, rather than opening a modal?

**Comment by snblickhan** [comment]
I'd be curious to know how it would present (even inline) for large chunks of text (thinking of the About section, etc.), which might look a bit nicer in a modal? Generally my thought is that the most helpful thing is to be able to view the original text next to the translated text, which the modal currently does, and I wouldn't want to lose or make less clear.

**Comment by eatyourgreens** [comment]
I've got a branch up at https://pandora.zooniverse.org/beta which opens the editor inline, so you can try it out.
