### ISSUE TITLE
Preview page being translated

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/pandora#94]
I wonder whether it's possible for the Preview button to map to the section being worked on, whether than defaulting to the front page? Just thinking of a use case in which someone is working on a tutorial and wants to immediately see how the tutorial looks, or a specific workflow, etc.

Not necessarily a priority atm, but something to consider.

**Comment by eatyourgreens** [comment]
Problem is the tutorial doesn’t have a URL that you can link to. The preview link is just a link to the project in PFE.
